# Generated by Django 5.1.7 on 2025-05-24 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelog',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_logs', to='academia.enrollment', verbose_name='enrollment'),
        ),
    ]
