# Generated by Django 5.1.7 on 2025-07-03 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0002_alter_attendancelog_enrollment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('name', 'surname')},
        ),
    ]
