# Generated by Django 5.1.7 on 2025-07-03 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0003_alter_student_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_number', models.PositiveIntegerField(help_text="The lesson number this grade refers to. If 'Exam', put 0.", verbose_name='lesson number')),
                ('grade', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='grade')),
                ('grade_type', models.CharField(choices=[('Leccion', 'Lesson'), ('Examen', 'Exam')], max_length=10, verbose_name='grade type')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='academia.enrollment', verbose_name='enrollment')),
            ],
            options={
                'verbose_name': 'grade',
                'verbose_name_plural': 'grades',
                'ordering': ['enrollment', 'grade_type', 'lesson_number'],
                'unique_together': {('enrollment', 'lesson_number', 'grade_type')},
            },
        ),
    ]
