# Generated by Django 5.1.7 on 2025-07-08 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0004_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('ENROLLED', 'Enrolled'), ('APPROVED', 'Approved'), ('REPROVED', 'Reproved'), ('COMPLETED', 'Completed'), ('DROPPED', 'Dropped Out')], default='ENROLLED', max_length=20, verbose_name='status'),
        ),
    ]
