# Generated by Django 5.1.7 on 2025-07-08 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0005_alter_enrollment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='homework_score',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='lesson_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average score for lessons (e.g., out of 100).', max_digits=5, null=True, verbose_name='lesson score'),
        ),
    ]
