# Generated by Django 5.1.7 on 2025-05-07 23:41

import cunakids.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('surname', models.CharField(max_length=128)),
                ('birthday', models.DateField(validators=[cunakids.models.validate_date])),
                ('parent_name', models.CharField(blank=True, max_length=128)),
                ('contact_phone', models.CharField(blank=True, max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='coordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('surname', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('description', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='assistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(validators=[cunakids.models.validate_date])),
                ('attended', models.BooleanField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cunakids.child')),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cunakids.coordinator')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cunakids.group')),
            ],
        ),
        migrations.CreateModel(
            name='server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('surname', models.CharField(max_length=128)),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cunakids.coordinator')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cunakids.group')),
            ],
        ),
    ]
