# Generated by Django 5.1.7 on 2025-06-30 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cunakids', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistance',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='child',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='assistance',
            unique_together={('child', 'date')},
        ),
    ]
