# Generated by Django 5.1.7 on 2025-06-30 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cunakids', '0002_alter_assistance_date_alter_child_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='status',
            field=models.CharField(choices=[('activo', 'Activo'), ('promovido', 'Promovido')], default='activo', max_length=10, verbose_name='Estado'),
        ),
    ]
