# Generated by Django 5.1.7 on 2025-07-03 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cunakids', '0003_child_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupCoordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cunakids.coordinator')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cunakids.group')),
            ],
            options={
                'verbose_name': 'Asignación Grupo-Coordinador (Cuna)',
                'verbose_name_plural': 'Asignaciones Grupo-Coordinador (Cuna)',
                'unique_together': {('group', 'coordinator')},
            },
        ),
    ]
