# Generated by Django 5.1.7 on 2025-07-27 01:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cunakids', '0004_groupcoordinator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinator',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Link this coordinator profile to a Django user account to allow login.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cunakids_coordinator', to=settings.AUTH_USER_MODEL, verbose_name='user account'),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='name',
            field=models.CharField(max_length=128, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='surname',
            field=models.CharField(max_length=128, verbose_name='surname'),
        ),
    ]
