# Generated by Django 5.1.7 on 2025-07-05 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
                ('description', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
                ('description', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('surname', models.CharField(max_length=128)),
            ],
            options={
                'unique_together': {('name', 'surname')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('attended', models.BooleanField()),
                ('adults', models.PositiveIntegerField(default=0, help_text='Número de adultos')),
                ('youngs', models.PositiveIntegerField(default=0, help_text='Número de jóvenes')),
                ('children', models.PositiveIntegerField(default=0, help_text='Número de niños')),
                ('autos', models.PositiveIntegerField(default=0, help_text='Número de autos')),
                ('note', models.TextField(blank=True, help_text='Observaciones o notas adicionales')),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anfitriones.coordinator')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anfitriones.group')),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anfitriones.ministry')),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('surname', models.CharField(max_length=128)),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anfitriones.coordinator')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anfitriones.group')),
            ],
            options={
                'unique_together': {('name', 'surname')},
            },
        ),
        migrations.CreateModel(
            name='Assistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('starthour', models.TimeField()),
                ('service', models.CharField(choices=[('PRI', 'Primero'), ('SEG', 'Segundo'), ('TER', 'Tercero')], default='PRI', max_length=3)),
                ('attended', models.BooleanField()),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anfitriones.server')),
            ],
        ),
    ]
