# Generated by Django 5.1.7 on 2025-07-05 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anfitriones', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assistance',
            unique_together={('server', 'date', 'service')},
        ),
    ]
