# Generated by Django 5.1.7 on 2025-05-24 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique code identifying the meeting.', max_length=50, unique=True, verbose_name='Code')),
                ('type', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], help_text='Specify if the meeting is for Male or Female participants.', max_length=1, verbose_name='Type')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the meeting.', null=True, verbose_name='Description')),
                ('date', models.DateField(help_text='Date on which the meeting takes place.', verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Meeting',
                'verbose_name_plural': 'Meetings',
                'ordering': ['-date', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('surname', models.CharField(max_length=128, verbose_name='surname')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='phone number')),
                ('date_of_birth', models.DateField(blank=True, help_text='Format: YYYY-MM-DD', null=True, verbose_name='date of birth')),
                ('height', models.PositiveIntegerField(blank=True, help_text='Height in centimeters (optional).', null=True, verbose_name='height')),
                ('address_reference', models.CharField(blank=True, max_length=256, null=True, verbose_name='address reference')),
                ('civil_status', models.CharField(blank=True, choices=[('SOLTERO', 'Single'), ('CASADO', 'Married'), ('DIVORCIADO', 'Divorced'), ('VIUDO', 'Widowed'), ('UNIÓN LIBRE', 'Union Free')], max_length=16, null=True, verbose_name='civil status')),
                ('notes', models.TextField(blank=True, help_text='Allergies, disabilities, medications, etc.', null=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Participant',
                'verbose_name_plural': 'Participants',
                'ordering': ['surname', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number (optional).', max_length=20, null=True, verbose_name='Phone Number')),
            ],
            options={
                'verbose_name': 'Server',
                'verbose_name_plural': 'Servers',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='FinanceMovements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_date', models.DateField(verbose_name='transaction date')),
                ('transaction_type', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense')], help_text='Specify if the transaction is an Income or Expense.', max_length=16, verbose_name='transaction type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('meeting_related', models.ForeignKey(blank=True, help_text='Optional: Link this transaction to a specific meeting.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_movements', to='encuentros.meeting')),
            ],
            options={
                'verbose_name': 'Financial Movement',
                'verbose_name_plural': 'Financial Movements',
                'ordering': ['-trans_date'],
            },
        ),
        migrations.CreateModel(
            name='FamilyParticipantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('surname', models.CharField(max_length=128, verbose_name='surname')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='phone number')),
                ('familiar_relationship', models.CharField(blank=True, max_length=32, null=True, verbose_name='familiar relationship')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='family_members', to='encuentros.participant')),
            ],
            options={
                'verbose_name': 'Family Participant Info',
                'verbose_name_plural': 'Family Participant Infos',
            },
        ),
        migrations.CreateModel(
            name='ChurchDataInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_member_of_church', models.BooleanField(default=False, verbose_name='is member of church')),
                ('church_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='church name')),
                ('is_baptized', models.BooleanField(default=False, verbose_name='is baptized')),
                ('baptism_date', models.DateField(blank=True, help_text='Format: YYYY-MM-DD', null=True, verbose_name='baptism date')),
                ('is_part_of_disciple_group', models.BooleanField(default=False, verbose_name='is part of disciple group')),
                ('name_of_leader', models.CharField(blank=True, max_length=128, null=True, verbose_name='name of leader')),
                ('is_part_of_bible_academy', models.BooleanField(default=False, verbose_name='is part of bible academy')),
                ('actual_subject', models.CharField(blank=True, max_length=128, null=True, verbose_name='actual subject')),
                ('is_registered_paid', models.BooleanField(default=False, verbose_name='is registered and paid')),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='amount paid')),
                ('payment_reference', models.CharField(blank=True, max_length=128, null=True, verbose_name='payment reference')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='church_data', to='encuentros.participant')),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assisted_church_infos', to='encuentros.server')),
            ],
            options={
                'verbose_name': 'Church Data Info',
                'verbose_name_plural': 'Church Data Infos',
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_end', models.DateField(verbose_name='period end')),
                ('income', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='total income')),
                ('expense', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='total expense')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='balance')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_summaries', to='encuentros.meeting')),
            ],
            options={
                'verbose_name': 'Financial Summary',
                'verbose_name_plural': 'Financial Summaries',
                'ordering': ['-period_end', 'meeting'],
            },
        ),
        migrations.CreateModel(
            name='MeetingParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(verbose_name='attendance date')),
                ('is_present', models.BooleanField(default=False, verbose_name='was present')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendees', to='encuentros.meeting')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meeting_attendances', to='encuentros.participant')),
            ],
            options={
                'verbose_name': 'Meeting Participant',
                'verbose_name_plural': 'Meeting Participants',
                'unique_together': {('meeting', 'participant', 'event_date')},
            },
        ),
    ]
