# Generated by Django 5.1.7 on 2025-07-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alabanza', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='coordinator',
            unique_together={('name', 'surname')},
        ),
        migrations.AlterUniqueTogether(
            name='server',
            unique_together={('name', 'surname')},
        ),
    ]
