# Generated by Django 5.1.7 on 2025-03-19 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('surname', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='fecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('week_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('description', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='groupage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
                ('description', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=64)),
                ('amount', models.FloatField()),
                ('reference', models.CharField(max_length=16)),
                ('fecha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pusukids.fecha')),
            ],
        ),
        migrations.CreateModel(
            name='kid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('surname', models.CharField(max_length=128)),
                ('birthday', models.DateField()),
                ('age', models.IntegerField()),
                ('parent_name', models.CharField(max_length=128)),
                ('contact_phone', models.CharField(max_length=16)),
                ('groupage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pusukids.groupage')),
            ],
        ),
        migrations.CreateModel(
            name='assistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField()),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pusukids.coordinator')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pusukids.fecha')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pusukids.group')),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pusukids.kid')),
            ],
        ),
        migrations.CreateModel(
            name='server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('surname', models.CharField(max_length=128)),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pusukids.coordinator')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pusukids.group')),
            ],
        ),
        migrations.CreateModel(
            name='weekinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pusukids.coordinator')),
                ('fecha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pusukids.fecha')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pusukids.group')),
            ],
        ),
    ]
