# Generated by Django 5.1.7 on 2025-05-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pusukids', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kid',
            name='age',
        ),
        migrations.AddField(
            model_name='weekinfo',
            name='money_collected',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='weekinfo',
            name='total_kids',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weekinfo',
            name='total_servers',
            field=models.IntegerField(default=0),
        ),
    ]
