# Generated by Django 5.1.7 on 2025-05-02 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pusukids', '0002_remove_kid_age_weekinfo_money_collected_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('surname', models.CharField(max_length=128)),
                ('birthday', models.DateField()),
                ('parent_name', models.CharField(blank=True, max_length=128)),
                ('contact_phone', models.CharField(blank=True, max_length=16)),
                ('groupage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pusukids.groupage')),
            ],
        ),
    ]
