# Generated by Django 5.1.7 on 2025-05-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pusukids', '0003_child'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kid',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='kid',
            name='parent_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.DeleteModel(
            name='child',
        ),
    ]
