# Generated by Django 5.1.7 on 2025-05-03 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pusukids', '0004_alter_kid_contact_phone_alter_kid_parent_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='kid',
            new_name='child',
        ),
        migrations.RenameField(
            model_name='assistance',
            old_name='kid',
            new_name='child',
        ),
    ]
