# Generated by Django 5.1.7 on 2025-05-03 15:13

import pusukids.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pusukids', '0005_rename_kid_child_rename_kid_assistance_child'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='birthday',
            field=models.DateField(validators=[pusukids.models.validate_date]),
        ),
        migrations.AlterField(
            model_name='fecha',
            name='date',
            field=models.DateField(validators=[pusukids.models.validate_date]),
        ),
    ]
