# Generated by Django 5.1.7 on 2025-05-06 01:45

import pusukids.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pusukids', '0006_alter_child_birthday_alter_fecha_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='transdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fecha',
            name='date',
            field=models.DateField(unique=True, validators=[pusukids.models.validate_date]),
        ),
    ]
