# Generated by Django 5.1.7 on 2025-07-03 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pusukids', '0007_expense_transdate_alter_fecha_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='status',
            field=models.CharField(choices=[('activo', 'Activo'), ('promovido', 'Promovido')], default='activo', max_length=10),
        ),
    ]
