# Generated by Django 5.1.7 on 2025-07-03 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pusukids', '0008_child_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='child',
            unique_together={('name', 'surname')},
        ),
    ]
