# Generated by Django 5.1.7 on 2025-07-03 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pusukids', '0009_alter_child_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assistance',
            unique_together={('child', 'date')},
        ),
    ]
