# Generated by Django 5.1.7 on 2025-07-03 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pusukids', '0010_alter_assistance_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupCoordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pusukids.coordinator')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pusukids.group')),
            ],
            options={
                'verbose_name': 'Asignación Grupo-Coordinador',
                'verbose_name_plural': 'Asignaciones Grupo-Coordinador',
                'unique_together': {('group', 'coordinator')},
            },
        ),
    ]
